### PR TITLE
fix: issue #7

### LINKED ISSUE #7: --ratio options v6.2.1 not working properly
After updating to the latest version, v6.2.1, I am encountering a problem with generating the --ratio files. It only happens when using the --sdf option.

If and when I have some spare time left. I will look in to it, but I don't know when that will be. You might want to fix it before that happens :) 

I am using the cli with command:
`spritezero sprite@4x ./svg --sdf --ratio=4`

**v6.2.0**
v6 2 0 @4x

**v6.2.1**
v6 2 1@4x

after downgrading back to v6.2.0 everything works again.

### PR DESCRIPTION
**Pull request by JinIgarashi**
fixes #7

### CODE REVIEW

**Comment by nickpeihl** [comment]
Thanks for the PR @JinIgarashi. It has been a long time since I have worked with this code. Do you have an example SVG that I can use to test this PR?

**Comment by JinIgarashi** [comment]
@nickpeihl I think any SVG can be used. There are svg files under test folder, I think these should be ok for testing.

**Comment by charlesbodman** [comment]
Would be nice to get this into the repo. Pretty big bug.

**Comment by nickpeihl** [comment]
@JinIgarashi Sorry for the delay here. Can you please [sign the contributor agreement](https://github.com/elastic/spritezero/pull/9#issuecomment-1687953096). We can not merge your PR until the agreement is signed.

**Comment by JinIgarashi** [comment]
@nickpeihl I just signed

**Comment by mikoding9** [comment]
Pardon me, is there any obstacle to merge this PR ? It is really needed

**Review by nickpeihl — APPROVED** [review]
changes lgtm! apologies for the delay in reviewing.

**Pull request merged**
